version: '3.5'

networks:
  ldap:
    driver: bridge
  portainer:
    driver: bridge

services:

  ### LDAP ###
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    restart: always
    ports:
      - ${LDAP_PORT}:389
      - 636:636
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_TLS=false
      - LDAP_TLS_ENFORCE=false
      - LDAP_TLS_VERIFY_CLIENT=never
    volumes:
      - ./ldap/ldif:/container/ldif
      - ./ldap/data/slapd/database:/var/lib/ldap
      - ./ldap/data/slapd/config:/etc/ldap/slapd.d
    networks:
      - ldap
    
  ### PHP LDAP ADMIN ###
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: always
    ports:
      - ${PHPLDAPADMIN_PORT}:80
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - ldap

  ### HEIMDALL ###
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    restart: always
    ports:
      - ${HEIMDALL_PORT}:80
      - ${HEIMDALL_SECURE_PORT}:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./heimdall/config:/config

  ### PORTAINER AGENT ###
  portainer_agent:
    image: portainer/agent
    container_name: portainer_agent
    restart: always
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer

  ### PORTAINER ###
  portainer:
    image: portainer/portainer
    ports:
      - ${PORTAINER_PORT}:9000
      - 8000:8000
    volumes:
      - ./portainer/data:/data
    networks:
      - portainer
